### PR TITLE
bug fix of library function

### PR DESCRIPTION
**Pull request by highright1234**
build.gradle.kts
```kts
dependencies {
  library(kotlin("stdlib-jdk8"))
}
bukkit.libraries = bukkit.libraries + listOf("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
```
before:
plugin.yml
```yml
libraries:
 - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
```
after:
```yml
libraries:
 - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
 - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10
```

### CODE REVIEW

**Comment by stephan-gh** [comment]
What is the use case for this? Why don't you simply do

```kotlin
dependencies {
  library("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
}
```

to also add the library to the compile classpath?

**Comment by highright1234** [comment]
> What is the use case for this? Why don't you simply do
> 
> ```kotlin
> dependencies {
>   library("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
> }
> ```
> 
> to also add the library to the compile classpath?

in my case
i should've do like runtimeOnly 
i am using the libraries that work like
```kts
dependencies {
    implementation("io.github.monun:kommand-api:<version>")
}
```
```
libraries:
  - io.github.monun:kommand-core:<version>
```
and i think my usages is simple than adding the library to the compile classpath

**Comment by stephan-gh** [comment]
I wonder if it would be better to have some kind of `runtimeLibrary` configuration in addition to `library`.

In any case, preserving the existing libraries in `bukkit.libraries` is probably reasonable. Can you try improving the commit message a bit so it is more clear what your commit is doing?

**Comment by highright1234** [comment]
I forgot to watch it. Sorry

**Pull request merged**
